DROP TABLE NOTES;
DROP TABLE STATS;

CREATE TABLE IF NOT EXISTS `STATS` (
  `STATSID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MILLIS` bigint(20) NOT NULL,
  `RXBYTES` bigint(20) NOT NULL,
  `TXBYTES` bigint(20) NOT NULL,
  `CREATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`STATSID`),
  KEY `CREATED_K` (`CREATED`),
  KEY `UPDATED_K` (`UPDATED`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=8;


CREATE TABLE IF NOT EXISTS `NOTES` (
  `NOTESID` bigint(20) NOT NULL AUTO_INCREMENT,
  `STATSID` bigint(20) NOT NULL,
  `NOTE` varchar(100) NOT NULL,
  `CREATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`NOTESID`),
  KEY `CREATED_K` (`CREATED`),
  KEY `UPDATED_K` (`UPDATED`),
  KEY `STATSID_FK` (`STATSID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4 ;

ALTER TABLE `NOTES`
  ADD CONSTRAINT `NOTES_IBFK_1` FOREIGN KEY (`STATSID`) REFERENCES `STATS` (`STATSID`)
  ON DELETE CASCADE ON UPDATE CASCADE;
  