#!/bin/bash

### Make sure any files created are group writable
umask 0002

### Configuration variables

# LOG_LVL=TRACE
# LOG_LVL=DEBUG
LOG_LVL=INFO

LOG_DIR=/var/log/snmpmon
LIB_DIR=/usr/share/snmpmon
VAR_DIR=/var/lib/snmpmon

DB_DIR=$VAR_DIR/db
GRAPH_DIR=$VAR_DIR/graph

CACTI_DB_DIR=$VAR_DIR/cacti_db
CACTI_GRAPH_DIR=$VAR_DIR/cacti_graph

CLASSPATH=$LIB_DIR/VMGraph.jar:\
$LIB_DIR/rrd4j-2.1.1.jar:\
$LIB_DIR/commons-cli-1.2.jar:\
$LIB_DIR/logback-core-1.0.2.jar:\
$LIB_DIR/logback-classic-1.0.2.jar:\
$LIB_DIR/slf4j-api-1.6.4.jar:\
$LIB_DIR/jcl-over-slf4j-1.6.4.jar:\
$LIB_DIR/log4j-over-slf4j-1.6.4.jar

### Generate graphs from rrdtool data generated by cacti
java\
 -Dlogback.configurationFile=logback_file_info.xml\
 -DLOG_LVL=$LOG_LVL\
 -DLOG_DIR=$LOG_DIR\
 -cp $CLASSPATH\
 uk.org.vacuumtube.rrd4j.VMGraph\
 -rrd_file $CACTI_DB_DIR/rb750gl_traffic_in_9.r4j\
 -profile XXL_50_5\
 -out_dir $CACTI_GRAPH_DIR\
 -rrdtool_file /var/lib/cacti/rra/rb750gl_traffic_in_9.rrd

### Generate graphs from native rrd4j data generated by SnmpGetService
java\
 -Dlogback.configurationFile=logback_file_info.xml\
 -DLOG_LVL=$LOG_LVL\
 -DLOG_DIR=$LOG_DIR\
 -cp $LIB_DIR/VMGraph.jar:$CLASSPATH\
 uk.org.vacuumtube.rrd4j.VMGraph\
 -rrd_file $DB_DIR/virgin.r4j\
 -profile XXL_50_5\
 -out_dir $GRAPH_DIR
