DROP TABLE NOTES;
DROP TABLE STATS;

CREATE TABLE IF NOT EXISTS `STATS` (
  `STATSID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MILLIS` bigint(20) NOT NULL,
  `RXBYTES` bigint(20) NOT NULL,
  `TXBYTES` bigint(20) NOT NULL,
  `CREATED` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00',
--  `UPDATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (`STATSID`),
  KEY `STATS_CREATED_K` (`CREATED`),
  KEY `STATS_UPDATED_K` (`UPDATED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `NOTES` (
  `NOTESID` bigint(20) NOT NULL AUTO_INCREMENT,
  `STATSID` bigint(20) NOT NULL,
  `NOTE` varchar(255) NOT NULL,
  `CREATED` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00',
--  `UPDATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (`NOTESID`),
  KEY `STATS_CREATED_K` (`CREATED`),
  KEY `STATS_UPDATED_K` (`UPDATED`),
  KEY `STATS_STATSID_FK` (`STATSID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `NOTES`
  ADD CONSTRAINT `NOTES_STATSID_IBFK` FOREIGN KEY (`STATSID`) REFERENCES `STATS` (`STATSID`)
  ON DELETE CASCADE ON UPDATE CASCADE;
  